### PR TITLE
Implementation of the skeletonize function for binary regions

### PR DESCRIPTION
**Pull request by aferust**
This is a rewrite of scikit-image's 2D fast skeletonized algorithm[1] written in cython. An example usage is also included in the examples folder.

1: https://github.com/scikit-image/scikit-image/blob/main/skimage/morphology/_skeletonize_cy.pyx

### CODE REVIEW

**Comment by 9il** [comment]
We need a reviewer for DCV

**Comment by aferust** [comment]
Sure. There must be an invite for review feature that I did not use before. Maybe you can invite the last contributors or PR owners for this purpose. Sadly, it looks like there are not many people involved in CV stuff within the D community.

**Comment by 9il** [comment]
@ljubobratovicrelja Do you wish to review the code? Otherwise, could @aferust continue maintain the repo in mir?

**Comment by ljubobratovicrelja** [comment]
Hi @aferust and @9il.

I am very happy to allow Ferhat to take over the maintenance of this project, as in number of occasions I've tried and failed to return to this project.

I'd gladly give this a review, but in order to do that properly, I'd have to clone the code and run in on my end, as I was for so long away from this project. I tried on Ferhat's last PR, and I didn't manage.

Therefore, Ferhat if you are willing to take over, please let me know and I'll happily give you the rights.

Cheers,
Relja

**Comment by aferust** [comment]
Dear Relja and Ilia, I can accept the ownership since DCV does not have too much traffic (PRs, issue reports, etc.), and it will not have it shortly I guess. I can carry the flag for a while. Please also note that this does not mean I can solve all the pre-existing issues related to the library shortly. I would even transfer it to someone else who is more willing to do it someday.

**Comment by ljubobratovicrelja** [comment]
@aferust sorry for not responding earlier, I am on a business trip with very little time for personal email, so your message skipped me. I've given you 'Maintainer' rights, hopefully this means that you can merge PRs by yourself. Please let me know if that's not the case.

**Pull request merged**
