### PR TITLE
Remove useless ndMap usage

### PR DESCRIPTION
**Pull request by 9il**

### CODE REVIEW

**Comment by ljubobratovicrelja** [comment]
Travis is failing. I've just ran into same problem earlier - assumeSameStructure cannot be packed. How can this be fixed?

**Comment by 9il** [comment]
Please report the bug with reduced test case
MN

**Comment by ljubobratovicrelja** [comment]
> Please report the bug with reduced test case

Will do tomorrow.

**Comment by 9il** [comment]
Thnx!

**Comment by 9il** [comment]
bug fix is ready. see https://github.com/dlang/phobos/pull/4781
Will note you when mir get it

**Comment by 9il** [comment]
should pass now

**Comment by ljubobratovicrelja** [comment]
Same problem exists in alpha7. Will you tag another version shortly at libmir/mir@8f617d68549c77c8f3e349323ff9542faa497413? This definitely solves the problem.

**Comment by 9il** [comment]
alpha8 should be available after few mins

**Comment by ljubobratovicrelja** [comment]
> alpha8 should be available after few mins

Awesome, tnx! I believe that's it. I'll wait for travis until it confirms a pass, than merge.

This fix will also allow [locksteps of packed tensors](https://github.com/ljubobratovicrelja/dcv/blob/master/source/dcv/imgproc/color.d#L221) to be turned to assumeSameStructure. Tnx!

**Comment by 9il** [comment]
@ljubobratovicrelja Passed now:-)

**Pull request merged**
