### PR TITLE
fix_dub

### PR DESCRIPTION
**Pull request by timotheecour**
update to allow compiling with recent versions of ggplotd

### CODE REVIEW

**Comment by 9il** [comment]
@ljubobratovicrelja current Mir version is 0.6.5

**Comment by timotheecour** [comment]
> current Mir version is 0.6.5

I dont' understand, could you be more precise? you mean mir-path or mir-algorithm?
the only `mir` entries in the dub.json were these (before this PR):
```
"mir-math": "~>0.0.1",
"mir-algorithm": "~>0.4.14"
```

**Comment by 9il** [comment]
> I dont' understand, could you be more precise? you mean mir-path or mir-algorithm?

mir-algorithm

**Comment by 9il** [comment]
BTW, mir-math is a part of mir-algorithm now

**Comment by timotheecour** [comment]
ok i see, thanks, will update this PR.
any way you could mark DEPRECATED for deprecate packages in dub descriptions?

```
dub search mir
==== registry at http://code.dlang.org/ ====
mir-internal (0.0.5)    Generic utilities for Mir projects
numir (0.0.3)           numpy-like API wrappers of mir
mir (1.1.0)             LLVM-accelerated Generic Numerical Library for Science and Machine Learning
mir-math (0.0.1)        Dlang Math Library
mir-blas (0.0.2)        NDSLICE wrapper for BLAS
mir-cpuid (0.5.2)       CPU characteristics identification
mir-random (0.2.5)      Dlang Random Number Generators
mir-lapack (0.0.3)      NDSLICE wrapper for LAPACK
mir-algorithm (0.6.5)   Multidimensional arrays (ndslice), ranges, iterators, and algorithms for Dlang
mir-glas (0.2.3)        Generic Linear Algebra Subprograms
```
i see mir-math indeed marked as deprecated in https://github.com/libmir but not in the above description.

also, is `mir` still relevant or deprecated? I'm guessing it's still relevant? The description:
`Sandbox for some mir packages: sparse tensors, Hoffman and others. The main repository is https://github.com/libmir/mir-algorithm` is ambiguous, it could mean that since main repo is `mir-algorithm` and this is a sandbox, it's not meant to be used?

**Comment by 9il** [comment]
mir is relevant

**Comment by 9il** [comment]
I will  remove mir-marh and mir-internal after this PR is merged

**Comment by 9il** [comment]
BTW, compiler versions in Travis should be updated too

**Comment by ljubobratovicrelja** [comment]
@timotheecour thanks for taking interest in dcv. :)

Could you please just update mir-algorithm to 0.6.5 then, and remove mir-math from dependencies? This change will be followed with some errors that would need fixing before merge (e.g mir.math.internal should be replaced with mir.math.common).

But anyhow, feel free to fix dcv enough so you can compile your project, and don't worry if travis is falling. Just say when you're done with your fixes, we'll merge, and I will see other details fixed in the following week. Hopefully until then you'll be able to use dcv master version in your project.
 

> BTW, compiler versions in Travis should be updated too

I'll fix this also.

**Comment by r4j4h** [comment]
@9il Regarding mir-math 

I think we need to replace most instances of [`import mir.math.internal`](https://github.com/libmir/mir-math/blob/master/source/mir/math/internal.d) with [`import mir.math.common`](https://github.com/libmir/mir-algorithm/blob/master/source/mir/math/common.d) as well

**Comment by timotheecour** [comment]
> Could you please just update mir-algorithm to 0.6.5

updated to latest 0.6.6

>  then, and remove mir-math from dependencies? This change will be followed with some errors that would need fixing before merge (e.g mir.math.internal should be replaced with mir.math.common).

done

**Comment by ljubobratovicrelja** [comment]
> done

Awesome. Let me know if I can merge this.

Not directly related to this PR - there's one issue (that I know of) in `dcv.features.utils.extractCorners` occurring in 2.074.0 - `topN` seems to be no longer `pure`. I'll fix this asap. After that I'll update compilers in travis, and after all passes with green flags, we'll make a new tag. @timotheecour you should be OK if you're using dmd 2.072.2.

**Comment by ljubobratovicrelja** [comment]
@9il could you take a look at travis dmd build? What is causing those linking errors?

**Comment by timotheecour** [comment]
Ok to merge, yes. Btw would love to chat via hangout if you have time, about DCV apis. Would be more efficient than cia github

**Comment by ljubobratovicrelja** [comment]
> Btw would love to chat via hangout if you have time, about DCV apis

No problem, I was about to offer any help you need. Feel free to contact me via hangout.

**Pull request merged**
