### PR TITLE
faster and nothrow random sample for RHT

### PR DESCRIPTION
**Pull request by 9il**

### CODE REVIEW

**Comment by 9il** [comment]
Btw, why array container is used in RHT?

**Comment by ljubobratovicrelja** [comment]
> Btw, why array container is used in RHT?

We may want to ping @DmitryOlshansky for this. Otherwise, @9il feel free to merge the changes yourself.

**Comment by 9il** [comment]
i did not change the algorithm, but RNG library.

@ljubobratovicrelja Do you have an visual example for RHT. RNG library is new, and it will be nice to have a proof that this PR does not introduce quality regression.

**Comment by ljubobratovicrelja** [comment]
> Do you have an visual example for RHT. RNG library is new, and it will be nice to have a proof that this PR does not introduce quality regression.

Yes, the example Dmitry's made shows the visual. Running examples/rht should create results similar as [this one](https://github.com/libmir/dcv/blob/master/examples/rht/result/rht.png).

**Comment by 9il** [comment]
> Yes, the example Dmitry's made shows the visual. Running examples/rht should create results similar as this one.

OK, it is the time for my first DCV installation :) How I can do it for OS X?

**Comment by ljubobratovicrelja** [comment]
> How I can do it for OS X?

Let me merge #93. Otherwise you'll have linking issues.

**Comment by 9il** [comment]
> Let me merge #93. Otherwise you'll have linking issues.

Do I need to install some libs before run dub for RHT example?

**Comment by ljubobratovicrelja** [comment]
> Let me merge #93. Otherwise you'll have linking issues.

You're good to go. 

> Do I need to install some libs before run dub for RHT example?

rht example links to whole dcv, but it needs only dcv:core. If you want, you can change it so it links only to dcv:core, and commit that here. That way you wont need anything preinstalled.

And in case you ever need ffmpeg and glfw, you'd might want to install ffmpeg using the [travis script](https://github.com/libmir/dcv/blob/master/scripts/travis_lib_setup.sh), and glfw3 should be ok to install with homebrew.

**Comment by DmitryOlshansky** [comment]
> Btw, why array container is used in RHT?

Can't recall the details but I think I needed reference semantics for the array, maybe it's possible with built-in arrays I just didn't spent too much time on it.

**Comment by ljubobratovicrelja** [comment]
@9il I'd like to draft a new release with recent changes. Would you like me to wait for this to be merged?

**Comment by 9il** [comment]
> @9il I'd like to draft a new release with recent changes. Would you like me to wait for this to be merged?

No, this is not urgent PR

**Comment by ljubobratovicrelja** [comment]
Merging this one... After full 5 years and some. :) Things are not working throughout the whole library, also rht examples do not compile because of changes within mir, so a lot of work to do.

**Pull request merged**
