### PR TITLE
update mir version

### PR DESCRIPTION
**Pull request by 9il**
ah, it is already here

### CODE REVIEW

**Comment by ljubobratovicrelja** [comment]
`Root package dcv:core reference mir ~>0.22.2 cannot be satisfied.`

Why is this happening? I've had this before with Mir, and never got concrete solution. Can this be a bug in dub?

**Comment by 9il** [comment]
it should be 0.22.0

**Comment by 9il** [comment]
Ahaha! it works!

**Comment by ljubobratovicrelja** [comment]
> Ahaha! it works!

Right on! :)

**Pull request merged**
