### PR TITLE
Fix logo and badges

### PR DESCRIPTION
**Pull request by ljubobratovicrelja**

### CODE REVIEW

**Comment by ljubobratovicrelja** [comment]
@9il after moving repo to libmir, to have corresponding gitter room, seems like we should open a new one. But since there's already well accustomed mir room, I believe there's no point in this, so I'd just like to remove previous gitter badge. Is that OK?

**Comment by 9il** [comment]
Yes, but why you do not want to add mir room to DCV's README?

**Comment by ljubobratovicrelja** [comment]
> Yes, but why you do not want to add mir room to DCV's README?

Ah, yes of course. Sorry, didn't thought of that. Will do.

**Comment by ljubobratovicrelja** [comment]
Added. Looks OK? Can we merge?

**Comment by 9il** [comment]
Yes, thanks!

**Pull request merged**
