### PR TITLE
Library sepearation

### LINKED ISSUE #25: Library separation
A user may want to use this library only for CV algorithms. Library should not force a user to install any C libraries.
Looks like DCV may be splitt to
- algorithms / image manipulations (DCV)
- decoding / codecs
- visualization

Current library looks like it is oriented for the end user. Comparing with Python, it is better practice  for D to have an API, which can be used to build extended functionality, e.g. to be used in other libraries and cross-platform products.

### PR DESCRIPTION
**Pull request by ljubobratovicrelja**
Working on #25.
## Library separated to following subPackages:
- core: core of the DCV, computer vision algorithms;
- io: image and video I/O;
- plot: visualization package.
## Main motivation:
- have modular library setup, and by that less dependencies for core module;
- having core module not depend on C libraries.
- ... there were more, can't remember at the moment..
## SubPackage dependencies:
- core
  - [mir](https://github.com/libmir/mir)
- io
  - core
  - [imageformats](https://github.com/lgvz/imageformats)
  - [ffmpeg-d](https://github.com/ljubobratovicrelja/ffmpeg-d)
- plot
  - core
  - [ggplotd](https://github.com/BlackEdder/ggplotd) (optional)
## Configurations:

To make ggplotd optional, [_ggplotd_](https://github.com/ljubobratovicrelja/dcv/blob/library-sepearation/dub.json#L81-L85) configuration has been added to dcv:plot package. And to make it optional on the global level, [_ggplotd_](https://github.com/ljubobratovicrelja/dcv/blob/library-sepearation/dub.json#L28-L34) configuration has been added to root package. So to use ggplotd stuff, `subConfiguration` has to be defined, like in some of the [examples](https://github.com/ljubobratovicrelja/dcv/blob/library-sepearation/examples/features/dub.json#L12-L15).

---

Pinging @DmitryOlshansky @9il @henrygouk all of you, since I feel this is a big change, and I'd like all of you to review it, and tell me what you think. 

**Note**: ggplotd configuration's name is not so lucky in mu opinion, but I'm not sure how better to name it. If anyone has a suggestion, fire away. 

One more **note**: There seam to be a bug in Dub in making this kind of setup. When setting up sub-packages like this, unittest-cov build gets messed up. This is actually copied from vibe.d's dub config as example, and there they offer a [workaround](https://github.com/rejectedsoftware/vibe.d/blob/master/dub.sdl#L23-L27). This is also applied [here](https://github.com/ljubobratovicrelja/dcv/blob/library-sepearation/dub.json#L15-L16), and seems to be working like a charm (until proven otherwise...).

---

Closes #25

### CODE REVIEW

**Comment by ljubobratovicrelja** [comment]
So, coverage is off. I'm trying to fix it, if anyone knows the straight solution, please help.

**Comment by 9il** [comment]
I think adding configuration is overengineering here. It is faster for user to add both sub-packages, then to define configuration.

Please split video (requires C) and image  (not requires C) io.

**Comment by ljubobratovicrelja** [comment]
> I think adding configuration is overengineering here. It is faster for user to add both sub-packages, then to define configuration.

To which configuration do you refer - one in the root? If so, than user which plans to use whole DCV, has to define either all three packages separately, either the root one and the plot, latter to define the subConfiguration, like so:

``` json
"dependencies": {
    "dcv": "",
    "dcv:plot": ""
},
"subConfigurations":{
    "dcv:plot": "ggplotd"
}
```

Of course he can define separated all three - maybe you're right, that'd be the cleanest way. @henrygouk and @DmitryOlshansky please tell us what you think of this matter.

> Please split video (requires C) and image (not requires C) io.

I like this. I will do it, @henrygouk @DmitryOlshansky please tell us if you have anything against it.

**Comment by 9il** [comment]
> Of course he can define separated all three - maybe you're right, that'd be the cleanest way. @henrygouk and @DmitryOlshansky please tell us what you think of this matter.

oh, never mind. I misunderstood config

**Comment by ljubobratovicrelja** [comment]
> Please split video (requires C) and image (not requires C) io.

How do we name image I/O and video I/O packages? Having only `image` and `video` might be misleading. Maybe `ioimage` and `iovideo`, but that seems too much. :) Ideas?

Are they subPackages of the package `io`, or do we simply split it into two packages? It'd be maybe better to make them subPackages of `io` since like that we'd follow existing project structure - that way it would be `dcv:io:image` and `dcv:io:video`, which seems ok to me. Otherwise I suggest we change that structure to fit the configuration.

**Comment by 9il** [comment]
another option is `io-image`, `io-video`

**Comment by henrygouk** [comment]
Is the image io portion of the library likely to remain free of C dependencies? Currently imageformats only supports writing 8 bit images, and the easiest way to add support to DCV for higher bit depth encoding would be to simply wrap an existing C library. Conveniently, ffmpeg is able to do this.

**Comment by ljubobratovicrelja** [comment]
> Is the image io portion of the library likely to remain free of C dependencies

My original plan was to do exactly what you propose- write minimal bindings to well known C libraries and by that support whole lot of formats with industry proven backend. Imageformats does support 16bit png and tga I think, but nevertheless I feel wrapping those libraries would be better choice. But that's a discussion for another thread, which I'll start latter in the day. 

Maybe postpone io splitting because of this dilemma?

**Comment by 9il** [comment]
OK

**Comment by 9il** [comment]
Have user ability to his own IO library?

**Comment by ljubobratovicrelja** [comment]
> Have user ability to his own IO library?

That would be really nice but I'm not sure how to realize this the right way. I suppose you think of some middle layer between dcv and io lib? Alternatively user can always handle himself the io,  slice read data and work along in dcv.

**Comment by 9il** [comment]
> Alternatively user can always handle himself the io, slice read data and work along in dcv.

Yes, this is what i whant.

**Comment by henrygouk** [comment]
> Imageformats does support 16bit png and tga I think

Imageformats can read 16 bit, but not write it.

> Maybe postpone io splitting because of this dilemma?

If by this you mean keeping the video and image packages as a single subpackage of DCV, then I agree.

**Comment by ljubobratovicrelja** [comment]
Ok I'll make an issue about this latter in the day then we'll discuss the details. 

I still have fix the codecov, in the meantime...

**Comment by ljubobratovicrelja** [comment]
Coverage is fine, so I'd like to merge this one. We haven't heard from @DmitryOlshansky, but I suppose he'd be fine we these changes.

Thanks guys!

**Pull request merged**
