### PR TITLE
Revision 2022

### PR DESCRIPTION
**Pull request by ljubobratovicrelja**
Continuation of #130.

To be merged as soon as possible, so that we can structure a new set of changes, one by one.

### CODE REVIEW

**Comment by ljubobratovicrelja** [comment]
@aferust I compiled the whole project, also built and ran video example without any issues. I think this is a good indicator that we should merge this, then introduce all the upcoming changes one by one, in every separate PR. If you agree, please give me a :+1: here, and I'll merge.

After that, we can get in contact to plan out what we do afterwards. First thing that comes to my mind is to address the `unrevised` directory, which I believe we can try and do it ourselves.

**Comment by aferust** [comment]
👍

**Comment by ljubobratovicrelja** [comment]
One major thank you @aferust for your contribution, and for getting this thing going again! ;)

**Comment by aferust** [comment]
Hi Relja,

Thank you for giving your valuable time to this. Separate imageio and videoio is a good idea. Just received so many notification e-mails from Github :) I need to follow up with them. 

I worked on the stereovision module last Friday a little bit, but I have not figured it out so far.  But I will keep trying.

I want to point out somethings before I forget it. 1) When I try reading and displaying data/building.png, it looks weird. I have to add data/building.jpg for related examples to work. 
2) Video example works with my webcam well. But centaur_1.mpg is being displayed with a distortion.

Can you try those examples with your configuration? You may reproduce those errors. If you reproduce too, we should open issues. You mentioned color-d before. The inclusion of it may resolve those issues?

**Comment by ljubobratovicrelja** [comment]
> I want to point out somethings before I forget it. 1) When I try reading and displaying data/building.png, it looks weird. I have to add data/building.jpg for related examples to work.

yes, something is likely outdated with png and imageformats, it seems. I am looking at it now, I have linking issues actually with examples regarding png.

> 2) Video example works with my webcam well. But centaur_1.mpg is being displayed with a distortion.
> Can you try those examples with your configuration? You may reproduce those errors. If you reproduce too, we should open issues.
 
Gonna look at it. I am on virtualbox, and a bit lazy to enable the webcam, but I will and test everything soon enough.

We need to make sure every example works - I guess that will be the biggest chunk of our update, as when these work, 99% of the library will work in any other context. I really tried hard to support every functionality of the library within these examples.

> You mentioned color-d before. The inclusion of it may resolve those issues?

Let's try to resolve all the deprecation, then we'll look at all things new - I doubt introducing anything new will resolve our existing issues, I think that'll be a harder path.

**Comment by aferust** [comment]
>We need to make sure every example works - I guess that will be the biggest chunk of our update, as when these work, 99% of the library will work in any other context. I really tried hard to support every functionality of the library within these examples.
I agree.

**Pull request merged**
