### PR TITLE
Dub review

### PR DESCRIPTION
**Pull request by ljubobratovicrelja**
Working on #26, plus few minor things.
- removed examples from dub.json
- further dub.json cleanup
- dub depenceny library version update
- removed scid as dependency - functionality will be in future replaced by Mir
- cleanup ci

### CODE REVIEW

**Comment by ljubobratovicrelja** [comment]
@9il I haven't added examples to unittest configuration like you said in #26 - to be honest, I'm not sure how to do it properly. Is this really necessary, or can we roll without them?

**Comment by 9il** [comment]
I mean Travis config only, not dub. You can see mir for example

**Comment by 9il** [comment]
Your 3x3 matrix inversion probably will be faster then lapack. What sizes you need for inversion?

**Comment by ljubobratovicrelja** [comment]
> I mean Travis config only, not dub. You see mir for example

Ah, ok, tnx!

> What sizes you need for inversion?

That's the only place I need inversion for now. I have added scid at start when I assumed it will be used more often. Hope there'll be no more need for inversion until it's present in Mir.

**Comment by ljubobratovicrelja** [comment]
@9il I'd like to call it a day. Merge OK? Also, can I close #26? I'd like to address to removing linking to C libraries in PR regarding #25.

**Comment by 9il** [comment]
LGTM

**Comment by ljubobratovicrelja** [comment]
Awesome, tnx for help!

closes #26

**Pull request merged**
